In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
# x = sigmoid func itself , not x in sig func
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#### Display Sigmoid & Derivative
import matplotlib.pylab as plt 
plt.style.use('ggplot')
x = np.arange(-8, 8, 0.1) 
a = sigmoid(x)
b = derivatives_sigmoid(a)
plt.plot(x, a) 
plt.plot(x, b) 
plt.xlabel('x') 
plt.ylabel('func(x)') 
plt.show()

<Figure size 640x480 with 1 Axes>

In [4]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [5]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) )  ## 4*3個
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [10]:
print('wh:\n{}'.format(wh))
print('---------------------------')
print('bh:\n{}'.format(bh))
print('---------------------------')
print('wout:\n{}'.format(wout))
print('---------------------------')
print('bout:\n{}'.format(bout))

wh:
[[0.15451572 0.14569171 0.82983478]
 [0.9022407  0.24420093 0.27286524]
 [0.36898899 0.39449576 0.4234552 ]
 [0.67060647 0.06604283 0.22136006]]
---------------------------
bh:
[[0.0130992  0.51326959 0.93787848]]
---------------------------
wout:
[[0.88596773]
 [0.67425493]
 [0.40042567]]
---------------------------
bout:
[[0.24995264]]


# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [22]:
for i in  range(epoch) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 

    output_layer_input1 = np.dot(hiddenlayer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid( output_layer_input )
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.88901269]
 [0.89413133]
 [0.88432525]]
wout,bout of Backpropagation:
[[0.80463524]
 [0.11501331]
 [0.87046048]],
[[0.60961513]]
